### ISSUE TITLE
[2.6.2] Specific Requirements

### ISSUE THREAD

**Issue by Claire1202** [BenjaminTham-SIT/INF2001_P4-5#105]
### About:

____________________________________________________________________________________________________________________________
### Goals:

____________________________________________________________________________________________________________________________
### Success - Completion Details:

____________________________________________________________________________________________________________________________
### Allocated Time:
 
____________________________________________________________________________________________________________________________
### Start date - End Date:
20/10 - 26/10
____________________________________________________________________________________________________________________________
### Person-in-charge:

- [ ] Benjamin
- [ ] Claire
- [ ] Claris
- [ ] Alyssa
- [ ] Megan

____________________________________________________________________________________________________________________________
### Task Status:

- [ ] In Progress
- [ ] Complete 
- [ ] Incomplete 

____________________________________________________________________________________________________________________________
### Priority:

- [ ] High Priority 
- [ ] Medium Priority 
- [ ] Low Priority

____________________________________________________________________________________________________________________________
### Notes:

**Comment by BenjaminTham-SIT** [comment]
New edits to requirements including FRs and UIRs. Certain requirements are not clear enough and had to be changed or rewritten and the ones that are too cluttered has been split.

![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/118095382/78a2d133-4f28-45fe-bf0d-d9306b06460c)
![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/118095382/ec92409d-f2df-4176-a7ba-5654a9b91df3)
![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/118095382/8cd0ca6c-5afd-49ad-b5a6-d7bc60c5360a)
![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/118095382/899aaf22-bdbd-406d-953c-d641c90e1dca)
