### ISSUE TITLE
[1.3.1c] Fomulate clientele questions

### ISSUE THREAD

**Issue by claris0911** [BenjaminTham-SIT/INF2001_P4-5#34]
### About:
For the first meeting with the client, questions need to be crafted for clarification or confirmations
____________________________________________________________________________________________________________________________
### Goals:

____________________________________________________________________________________________________________________________
### Success - Completion Details:

____________________________________________________________________________________________________________________________
### Allocated Time:
 
____________________________________________________________________________________________________________________________
### Start date - End Date:

____________________________________________________________________________________________________________________________
### Person-in-charge:

- [ ] Benjamin
- [ ] Claire
- [x] Claris
- [ ] Alyssa
- [ ] Megan

____________________________________________________________________________________________________________________________
### Task Status:

- [ ] In Progress
- [x] Complete 
- [ ] Incomplete 

____________________________________________________________________________________________________________________________
### Priority:

- [x] High Priority 
- [ ] Medium Priority 
- [ ] Low Priority

____________________________________________________________________________________________________________________________
### Notes:
Questions formed are in the shared document

**Comment by claris0911** [comment]
1. would the information on the system be taken from a database or uploaded from an excel sheet or- 
2. can give sample of data
3. under the assumption that your teacher/class count may increase/decrease in the future
4. confirm if the main access roles on the applications are: teachers and admins, managers
5. is there any file(?) that needs to come out at the end of the process?
6. given the access roles, could you kind of tell us the restrictions per role?
7. what happens when teachers cannot make it for their classes last min (i.e. sick, personal issues)
8. how to deal with late availability submissions
9. how to deal with lack of teaching staff (or is this not our problem)
10. how to check if teachers turn up for their shifts (or is this not our problem)
11. under the assumption the music school students are having classes once every week?
12. are students assigned to a specific teacher or can the teacher change depending if the teacher is on schedule for the week?

====================

1. given the base list of requirements, which ones would you consider non-negotiable or which ones are “nice to have”
2. in regards to documentation, extensive or not a priority (i would assume not a priority but nice to have)
3. confirm their process flow is as we understand
4. prior to our system, how have they been doing things
5. do you have any restrictions (budget/time)
6. we need to decide on the minimum viable product and get client to agree
7. what are the security concerns that may be an issue in the system or management of employee personal data
8. any linkage to any external system (workday, google calendar)

**Comment by 2202528** [comment]
Functional Questions

1. When a staff puts in their job preference for the week, does it mean that for this particular week, for Mon-Sun, they would prefer to teach a specific subject like piano for the whole week?
4. How many weeks in advance must a manager schedule jobs for a particular week? Like for Week 7, must he schedule by Week 3 Sunday 2359?
5. Can the manager last minute allocate the day before?
6. Are the staff allowed to change their availabilities up to the day before the current week?
7. How would job preference for the week be implemented? Like in their dashboard, there is a calendar to show overall workload for the month/weekly so like for the weekly section, for each week they can put their job preference?
8. How to handle employee missing the deadline? Does case by case basis means a section or list or page to handle missing deadlines?

**Comment by Claire1202** [comment]
Functional Questions

i. should the shifts be displayed by the timings that the employees chose, or the specific roles that they have? 
ii. for the top 3 staff lowest workload, is it throughout a week or a month? 
iii. can the employees switch their shifts with one another on the day before? 
iv. is there a limit to the number of hours an employee can choose per day/ a week? 
v. can the manager change the shifts for the employees?

**Comment by itsalys** [comment]
Functional Questions

1. Is preference stated when availability is stated? Can staff state preference for each individual class, day, or week? 
2. For Manager's View, should workload be displayed for the day, week or month? 
3. To visualise staff workload, organise by teacher or by room? should focus on each individual teacher’s working schedule or the schedule for that room? 
4. And if focus is on the teacher 's working schedule, can it be shown in shifts(10am-2pm) or must state job assignments? 
5. If the workload is supposed to be shown by workload per teacher, will the workload be assigned and displayed as shifts(10-2) or separate 30-minute blocks?
