### ISSUE TITLE
[1.3.1d] Produce Visual Aids

### ISSUE THREAD

**Issue by 2202528** [BenjaminTham-SIT/INF2001_P4-5#8]
### About:
This task is for the assignees to create wireframe examples of the final prototype. Wireframes can either be drawn physically, digitally or use with drawing programs like Figma. Wireframes are to show the layout and contents of the final prototype, which would be a website. Wireframes do not need to be detailed.
____________________________________________________________________________________________________________________________
### Goals:
There should be wireframes for all user types, which are Manager, Staff and IT Admin. 
Wireframes should show layout of pages for each user. For example, the Manager Dashboard wireframe should show the layout of the page and the contents meant to be in the page (through text notations or visual examples).

____________________________________________________________________________________________________________________________
### Success - Completion Details:

____________________________________________________________________________________________________________________________
### Allocated Time:
4 Days
____________________________________________________________________________________________________________________________
### Start date - End Date:
3 Sep - 7 Sep

____________________________________________________________________________________________________________________________
### Person-in-charge:
- [ ] Benjamin
- [ ] Claire
- [ ] Claris
- [ ] Alyssa
- [x] Megan
______________
____________________________________________________________________________________________________________________________
### Task Status:
- [ ] In progress 
- [x] Completed
- [ ] Incomplete
____________________________________________________________________________________________________________________________
### Priority:
- [ ] High Priority 
- [x] Medium Priority 
- [ ] Low Priority 
- [ ] Overdue
____________________________________________________________________________________________________________________________

**Comment by itsalys** [comment]
### Work Done:

Draft Wireframe for employee interface

Employee Dashboard V1: Monthly View


![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/69067945/b9f8d585-0bbc-46c3-80ac-66255ec5ea76)



Employee Dashboard V2: Weekly & Monthly View


![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/69067945/e7639159-5203-4f06-9702-cb0ec46dc42c)


Employee Dashboard V3: Weekly without Availability


![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/69067945/d4d6c066-1d8d-4cee-aef8-4f0acd652ba0)


Employee Dashboard V4: Weekly with Availability


![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/69067945/4a57f780-16c3-45f5-bc9f-2079b383c46f)


Employee Job Allocation V1: List View


![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/69067945/cc82e5e1-981e-45ca-8a4a-e71e4f2bd9e1)


Employee Job Allocation V2: Table View



![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/69067945/607ef975-3bde-4fa3-8c6e-af43d9b6c024)



____________________________________________________________________________________________________________________________
### Repository Commit status:
no commit

____________________________________________________________________________________________________________________________
### Completion Deadline Effect:

____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)


____________________________________________________________________________________________________________________________
### Start Date - End Date:

**Comment by 2202528** [comment]
**Created Mockups for M1 Report**

In addition to the wireframes created for the client meeting, I also created wireframes for the M1 Report. These 3 wireframes were for the Manager Dashboard, the Employee Dashboard and for the Employee Job Allocation page.

**Manager Dashboard - With Annotations** 

![manager wireframe](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/111504470/ad436548-72d5-45dd-a4a9-ce5782912f73)

**Manager Dashboard - Without Annotations** 

![manager dashboard](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/111504470/2f8ca748-79bb-4330-87cf-6addb0316092)

Description: This wireframe represents the dashboard of the Manager where the workload of employees would be displayed by  employee shifts. The top 3 employees with the least workload and all the staff with a workload of over 40 hours per week would also be displayed in the Dashboard.

**Employee Dashboard - With Annotations** 

![employee dashboard wireframe](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/111504470/57c5edc8-013b-4fad-8a5a-b1e17dc46f2b)

**Employee Dashboard - Without Annotations** 

![employee dashboard](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/111504470/dc60c9c5-ea46-4d80-8046-7f2d8857ca98)

Description: This wireframe represents the dashboard of the Employee where the workload of the employee will be displayed via a calendar, by week or by month. The percentage of how many allocated jobs contained the employee's preferred instrument and preferred timing is also shown.

**Employee Job Allocation - With Annotations** 

![employee job allocation wireframe](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/111504470/d584fb08-c833-49f5-99e6-c499c0543421)

**Employee Job Allocation - Without Annotations** 

![employee job allocation (assigned jobs)](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/111504470/62f18eb5-eb40-446a-8adf-ff0292979ccd)

Description: This wireframe represents the Job Allocation page of the Employee. The Job Allocation page has 3 sub pages, one for the employee's allocated jobs, one for the employee's job availabilities and another for their preferences. This wireframe shows the sub page for the employee's allocated jobs.

**Comment by Claire1202** [comment]
Work Done:
Draft Wireframe for IT Admin interface

IT Admin Dashboard V1: Staff and Managers details

![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/115334872/3ebe380e-46d4-4b42-8a1a-927833b5a4c8)
