### ISSUE TITLE
[2.1.2a] Setup common files

### ISSUE THREAD

**Issue by 2202528** [BenjaminTham-SIT/INF2001_P4-5#81]
### About:
Setting up common file sharing channel on google drive/
____________________________________________________________________________________________________________________________
### Goals:
- setup common file sharing channels
____________________________________________________________________________________________________________________________
### Success - Completion Details:

- [x] setup google file milestone 2

____________________________________________________________________________________________________________________________
### Allocated Time:
 1 day
____________________________________________________________________________________________________________________________
### Start date - End Date:
25/9 - 25 /9
____________________________________________________________________________________________________________________________
### Person-in-charge:

- [ ] Benjamin
- [ ] Claire
- [ ] Claris
- [ ] Alyssa
- [x] Megan

____________________________________________________________________________________________________________________________
### Task Status:

- [ ] In Progress
- [x] Complete 
- [ ] Incomplete 

____________________________________________________________________________________________________________________________
### Priority:

- [x] High Priority 
- [ ] Medium Priority 
- [ ] Low Priority

____________________________________________________________________________________________________________________________
### Notes:

**Comment by BenjaminTham-SIT** [comment]
### Work Done:
cleaned up google drive. added new m2 deliverables and materials folder.
____________________________________________________________________________________________________________________________
### Repository Commit status:
no commit
____________________________________________________________________________________________________________________________
### Completion Deadline Effect:

____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)
[25/9/2023] - created google files for m2 deliverables 
[25/9/2023] - created google files for m2 materials
[25/9/2023] - archived m2 materials

____________________________________________________________________________________________________________________________
### Start Date - End Date:
25/9 - 25/9
