### ISSUE TITLE
[2.1.2b] Setup common workspace

### ISSUE THREAD

**Issue by 2202528** [BenjaminTham-SIT/INF2001_P4-5#82]
### About:
General setup of certain project tools like figma and lucidchart.
____________________________________________________________________________________________________________________________
### Goals:
- setup common tools
____________________________________________________________________________________________________________________________
### Success - Completion Details:

- [x] setup lucid chart milestone 2
- [x] setup figma milestone 2

____________________________________________________________________________________________________________________________
### Allocated Time:
 1 day
____________________________________________________________________________________________________________________________
### Start date - End Date:
25/9 - 25 /9
____________________________________________________________________________________________________________________________
### Person-in-charge:

- [ ] Benjamin
- [ ] Claire
- [ ] Claris
- [ ] Alyssa
- [x] Megan

____________________________________________________________________________________________________________________________
### Task Status:

- [ ] In Progress
- [x] Complete 
- [ ] Incomplete 

____________________________________________________________________________________________________________________________
### Priority:

- [x] High Priority 
- [ ] Medium Priority 
- [ ] Low Priority

____________________________________________________________________________________________________________________________
### Notes:

**Comment by 2202528** [comment]
### Work Done:
Created the Figma link for M2:

https://www.figma.com/file/qRA9vcI1TF5PzkCK3M9Uwb/inf2001-wireframes-M2?type=design&node-id=0-1&mode=design&t=phfCiv66g7KLm3E1-0
____________________________________________________________________________________________________________________________
### Repository Commit status:
No commit
____________________________________________________________________________________________________________________________
### Completion Deadline Effect:
Complete
____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)
25/9/2023 - Set up the Figma

____________________________________________________________________________________________________________________________
### Start Date - End Date:
25/9 - 25/9

**Comment by claris0911** [comment]
### Work Done:
Setup the Lucid link for M2:

https://lucid.app/lucidchart/34fe3db6-9f3f-456f-a071-5fd760b9c2d3/edit?viewport_loc=-4312%2C-1664%2C8000%2C3556%2C0_0&invitationId=inv_5ec1415a-2d0a-4bc1-b58f-59c8c1a77eb2
____________________________________________________________________________________________________________________________
### Repository Commit status:
No commit
____________________________________________________________________________________________________________________________
### Completion Deadline Effect:
Complete
____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)
25/9/2023 - Set up the Lucid Chart

____________________________________________________________________________________________________________________________
### Start Date - End Date:
25/9 - 25/9
